// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Aaw7X81q6aD8Xh7fpGSKe9ewkon3v4w',
    appId: '1:494840137499:web:04e34980e5fcd5f40875be',
    messagingSenderId: '494840137499',
    projectId: 'innsight-a1a34',
    authDomain: 'innsight-a1a34.firebaseapp.com',
    storageBucket: 'innsight-a1a34.firebasestorage.app',
    measurementId: 'G-R3XEWF4P7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFXiXCffP_9MGGdwqm8GRYM6bB3h1GFOI',
    appId: '1:494840137499:android:e51d0e6889b908f70875be',
    messagingSenderId: '494840137499',
    projectId: 'innsight-a1a34',
    storageBucket: 'innsight-a1a34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANIiyt5t3ynhJrWdGmU1HJElMVuLqDhHc',
    appId: '1:494840137499:ios:5858ca118c01633f0875be',
    messagingSenderId: '494840137499',
    projectId: 'innsight-a1a34',
    storageBucket: 'innsight-a1a34.firebasestorage.app',
    androidClientId: '494840137499-lkbohk10j01f68uri78asvp4k34hjdro.apps.googleusercontent.com',
    iosClientId: '494840137499-geccv3mpqdfdv086ed7gntersv3jjnb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.innsight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANIiyt5t3ynhJrWdGmU1HJElMVuLqDhHc',
    appId: '1:494840137499:ios:5858ca118c01633f0875be',
    messagingSenderId: '494840137499',
    projectId: 'innsight-a1a34',
    storageBucket: 'innsight-a1a34.firebasestorage.app',
    androidClientId: '494840137499-lkbohk10j01f68uri78asvp4k34hjdro.apps.googleusercontent.com',
    iosClientId: '494840137499-geccv3mpqdfdv086ed7gntersv3jjnb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.innsight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Aaw7X81q6aD8Xh7fpGSKe9ewkon3v4w',
    appId: '1:494840137499:web:56d256419444994b0875be',
    messagingSenderId: '494840137499',
    projectId: 'innsight-a1a34',
    authDomain: 'innsight-a1a34.firebaseapp.com',
    storageBucket: 'innsight-a1a34.firebasestorage.app',
    measurementId: 'G-CXZ7801QLT',
  );
}
